# Site settings

title:  Peter_Andersson
twitter_username:  fshsweden
name:  Peter Andersson

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://fsh.se
 - title: GitHub
   url: https://github.com/fshsweden
 - title: StackOverflow
   url: http://stackoverflow.com/users/587238/peter-andersson
 - title: DZone
   url: https://dzone.com/users/405821/fshsweden.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/peterandersson
   
#Any buzzword skills you want to include
skills:
 - Java
 - Linux, installation och administration
 - Ruby och Ruby on Rails
 - Javascript, Coffeescript, Typescript
 - C#, Azure, Service Fabric, ASP MVC, Web API
 - Groovy
 - JQuery, React, Angular
 - Node.js, npm, yarn
 - Maven, Ant, Gradle
 - SQL, MySQL, Postgres, SQLite
 - REST, Api-design
 
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default
blogfeed: https://fsh.se/feed

#Work experience is required
roles:
 - title: Programmerare/Designer
   start: Feb 2017
   end: 
   employer: FSH Sweden AB
   description: Alpha Trading - an automatic stock and futures trading system. NASDAQ, NYSE, AMEX, SFB etc. Java MySQL på OSX Linux Windows 
 - title: Programmerare
   start: Nov 2016
   end: Jan 2017
   employer: SaveLend AB
   description: Hjälpte till med leverans av gravt försenat system + systemdokumentation
 - title: Systemanalys av säljverktyg
   start: April 2016
   end: Maj 2016
   employer: Gadder AB
   description: Analyserade ett existerande system, identifierade svagheter och utfärdade rekommendation för hur fortsatt utveckling skulle ske
 - title: Designer och programmerare. 
   start: April 2014
   end: September 2016
   employer: Crozet AB
   description: Alpha Trading - an automatic stock and futures trading system. NASDAQ, NYSE, AMEX, SFB etc. Java MySQL på OSX Linux Windows 
 - title: Programmerare 
   start: April 2013
   end: Mars 2014
   employer: FSH Sweden AB
   description: Ett flertal mindre konsultuppdrag, men även en stor del fritid där jag bl.a lärde mig Ruby on Rails samt ett flertal Javascript-verktyg och olika ramverk som Meteor och Laravel
 - title: System Arkitekt
   start: Mars 2010
   end: Mars 2013
   employer: Jones Borreguero Inversiones SL, Madrid
   description: Skapade en helautomatisk handlarapplikation som handlade IBEX-optioner på MEFF-börsen i Madrid. Designade och implementerade en standalone Java applikation som kommunicerade med Orc Trader (via Orc Protocol) och MEFF med hjälp av  FIX 4.4. Hanterade parametersättning från Orc Trader och beräknade teoretiska priser (Black&Scholes och Binomial tree model) på alla optioner. Exekverade orders automatiskt när möjlighet fanns att tjäna riskfria pengar (arbitrage). Användes I produktion mellan Jan 2011 och våren 2014. Språk och miljöer var OSX, Java, Swing, MySQL
 - title: System Arkitekt
   start: Juni 2009 
   end: Januari 2010
   employer: 
   description: Deltog i designen av ett större tradingsystem. Systemet omfattade en generell tradingmodell som kan appliceras på alla elektroniska börser. Egenskaper värda att nämnas är realtidsvärdering av derivat mm samt riskhantering i realtid. Systemet kan dessutom hantera handel i olika valutor samt strukturerade konton/books, med s.k. hedging på flera nivåer. Konton kan hanteras av flera traders (stafettmodell) och därmed ge möjlighet till handel/riskhantering hela dygnet över hela världen. En avancerad distributionsmodell för priser/information ingår också. Systemet implementerades aldrig pga ändrade marknadsförutsättningar och minskade handelsvolymer. 
 - title: System Arkitekt
   start: Januari 2006
   end: Maj 2009
   employer: 68 Technologies AB
   description: Designade och implementerade ett “Home Control” system med video streaming. Ledde ett team på 5 personer, varav 3 kinesiska konsulter i implementationen av främst nätverksdelen, servrarna, meddellandeprotokollet och klient-API:et. Systemet vidareutvecklades senare till qrodo.com, som sände live-video från bl.a. svenska speedwayserien, bordtennis, badminton med mera med mera. Qrodo.com lades ner 2015.
 - title: System Manager
   start: Januari 1997 
   end: December 2005
   employer: FSH Zug AG / FSH Sweden AB
   description: Designade, implementerade och skötte driften av ett avancerat fleranvändasystem för handel av derivat. C:a 10 användare på två kontor, Zug (Schweiz) och Madrid (Spanien).  Riskhantering I realtid, flera automathandelsapplikationer samt en vid den tiden världsledande handlarapplikation. Första 5 åren i Schweiz, resten i Gävle.
 - title: Systemansvarig för OM:s (numera NASDAQ) handlarapplikation på Windows (“Click Trade”)
   start: Maj 1994
   end: December 1996
   employer: OM Technology AB
   description: Porterade OMex Click Trade från VAX/VMS till Windows NT 1.0. Modifierade och vidareutvecklade mjukvaran med handelsfunktioner för bl.a ränteoptioner. Blev systemansvarig för Click Trade i OMex-systemet. Deltog i försäljning av OMex till bl.a ASX i Sydney och CBOT och CME i Chicago.
 - title: Konsult, Projektledare
   start: Maj 1991
   end: Maj 1994
   employer: WM-Data Teknikkonsult AB
   description: Konsult I C/C++, bl.a mot Landstinget i Stockholm. Projektledare i ett flertal projekt, t.ex mot Rikspolisstyrelsen (ekonomienheten).
 - title: Konsult
   start: Oktober 1988
   end: December 1990
   employer: Ardencia AB
   description: IT-konsult, huvudsakligen i C och C++. Produktutveckling för Bonniers, SIX, FinData, Nyhetsbyrån Direkt, Dagens Industri etc.
 - title: Konsult
   start: April 1986
   end: September 1988
   employer: Fyra Linjer AB
   description: Konsult, huvudsakligen i DataFlex, Turbo Pascal och C. Kunder var Landstinget, Ericsson, ODAB mfl. Utvecklade en editor för DataFlex som marknadsfördes och såldes av företaget

#Education is required
education:
 - level: 
   date: 
   subject: 
   school: 

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#List of interesting Github repo/projects to include - optional
github:
 - fshsweden/FinTools
 - fshsweden/AnalyzeIt
 - fshsweden/IB-api-972-beta-feb03-modified
 - fshsweden/IB-API
 
#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/587238/peter-andersson
   flairimageurl: http://stackoverflow.com/users/flair/587238.png

#Mobile apps section is optional
apps:
 - name: Valbo HC Istider 2012 (now removed)
   platform: IOS
   url: 
   description: Ett system för att se bokningar av Valbo ishall
 - name: Flappy Felipe (now removed)
   platform: IOS
   url: 
   description: En enkel Flappy Birds-klon

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   Jag är mycket intresserad av programspråk/ramverk och miljöer, så jag tittar på så många jag kan. 
   Nyligen har jag gjort flera saker i JS/ES6/Typescript. Främst Angular, React och Meteor.
